import streamlit as st
import pandas as pd
import plotly.express as px
import numpy as np

# Page config
st.set_page_config(
    page_title="Sales Performance Dashboard - Update-24 Tech",
    page_icon="📊",
    layout="wide"
)

# Custom CSS – premium branding
st.markdown("""
    <style>
    .main { background-color: #f8f9fa; padding-bottom: 100px; }
    h1, h2, h3 { color: #0A2540 !important; font-family: 'Segoe UI', sans-serif; }
    .stMetric {
        background: white;
        border-radius: 12px;
        box-shadow: 0 4px 15px rgba(10, 37, 64, 0.08);
        padding: 1.5rem;
        text-align: center;
        border-left: 5px solid #00B4D8;
    }
    .stMetric label { color: #555; font-size: 1rem; font-weight: 500; }
    .stMetric .stMetric-value { color: #0A2540; font-size: 2.2rem; font-weight: 700; }
    .footer {
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        background-color: #0A2540;
        color: white;
        text-align: center;
        padding: 1rem;
        font-size: 0.95rem;
        z-index: 100;
    }
    hr { border-color: #e0e0e0; margin: 2rem 0; }
    </style>
""", unsafe_allow_html=True)

# Title
st.title("📊 Sales Performance Dashboard")
st.markdown("**Real-time overview of business performance** — Generated by Update-24 Tech Services")

# Generate realistic mock data (30 days in January 2025)
np.random.seed(42)  # For consistent results during demo
dates = pd.date_range(start="2025-01-01", periods=30, freq="D")
base_revenue = np.random.normal(3000, 800, 30).clip(1200, 5500)
trend = np.linspace(0, 1500, 30)  # Upward trend
seasonal = 500 * np.sin(np.linspace(0, 4*np.pi, 30))  # Weekly cycle
revenue = (base_revenue + trend + seasonal).round(0).astype(int)

daily_df = pd.DataFrame({
    "Date": dates,
    "Revenue": revenue
})

# KPI calculations
total_revenue = daily_df["Revenue"].sum()
total_transactions = int(len(daily_df) * np.random.uniform(4.5, 7.5))  # Approx 5–7 tx/day
avg_daily = total_revenue / len(daily_df)
growth = ((daily_df["Revenue"].iloc[-1] - daily_df["Revenue"].iloc[0]) / daily_df["Revenue"].iloc[0] * 100)

# KPI cards
col1, col2, col3, col4 = st.columns(4)
col1.metric("Total Revenue", f"₦{total_revenue:,.0f}")
col2.metric("Total Transactions", f"{total_transactions:,}")
col3.metric("Avg Daily Revenue", f"₦{avg_daily:,.0f}")
col4.metric("Growth Rate", f"{growth:+.1f}%", delta_color="normal")

# Daily Revenue Trend
st.markdown("### 📈 Daily Revenue Trend (January 2025)")
fig_trend = px.line(
    daily_df,
    x="Date",
    y="Revenue",
    title="Daily Sales Performance",
    labels={"Revenue": "Revenue (₦)"}
)
fig_trend.update_traces(line=dict(width=3.5, color="#00B4D8"))
fig_trend.update_layout(
    showlegend=False,
    xaxis_title="Date",
    yaxis_title="Revenue (₦)",
    hovermode="x unified"
)
st.plotly_chart(fig_trend, use_container_width=True)

# Top 5 Products (mock data)
top_products = pd.DataFrame({
    "Product": ["Rice", "Beans", "Vegetable Oil", "Garri", "Sugar"],
    "Revenue": [85000, 72000, 58000, 49000, 42000]
}).sort_values("Revenue", ascending=False)

st.markdown("### 🔥 Top 5 Best-Selling Products")
fig_bar = px.bar(
    top_products,
    x="Revenue",
    y="Product",
    orientation="h",
    title="Top Performers by Revenue",
    color="Revenue",
    color_continuous_scale="blues"
)
fig_bar.update_layout(showlegend=False)
st.plotly_chart(fig_bar, use_container_width=True)

# Footer
st.markdown("""
    <div class="footer">
        Built by <strong>Update-24 Tech Services</strong> — Intelligent Digital Solutions | Web • Mobile • AI • Data
    </div>
""", unsafe_allow_html=True)